import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const starter = JSON.parse(readFileSync('public/examples/h3-starter.api.json', 'utf8'));
let mockTarget = '';
test.beforeAll(async ({ request }) => { mockTarget = (await (await request.get('/api/connection')).json()).target; });
test.beforeEach(async ({ request, page }) => { await page.addInitScript(prompt => { if (!localStorage.getItem('sceneweaver.project.v1')) localStorage.setItem('sceneweaver.project.v1', JSON.stringify({ name: 'Offline test', prompt, bindings: {}, warnings: [] })); }, starter); await request.put('/api/connection', { data: { target: mockTarget } }); await request.post('/comfy/test/reset'); });
test('edits a scene, queues the exact prompt, reviews takes, and restores local changes', async ({ page, request }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Render workflow', exact: true })).toBeEnabled();
  await page.getByRole('textbox', { name: 'Scene direction', exact: true }).fill('A revised scene with exact visual continuity.');
  await page.getByRole('button', { name: 'Render workflow', exact: true }).click();
  await expect(page.getByText('Queued', { exact: true })).toBeVisible();
  const state = await (await request.get('/comfy/test/state')).json();
  expect(JSON.parse(state.submissions[0].prompt['1700'].inputs.plan_json).shots[0].prompt).toBe('A revised scene with exact visual continuity.');
  expect(state.submissions[0].client_id).toBeTruthy();
  await request.post('/comfy/test/review');
  await expect(page.getByText('Awaiting your review')).toBeVisible();
  await page.getByRole('button', { name: 'Approve & continue', exact: true }).click();
  await expect(page.getByText('Awaiting your review')).not.toBeVisible();
  const reviewed = await (await request.get('/comfy/test/state')).json();
  expect(reviewed.decisions[0]).toMatchObject({ action: 'approve', candidate_revision: 'take-2', candidate_revisions: ['take-1', 'take-2'], seed: '18446744073709551615' });
  await page.getByRole('button', { name: 'Close render queue' }).click();
  await page.waitForTimeout(650); await page.reload();
  await expect(page.getByRole('textbox', { name: 'Scene direction', exact: true })).toHaveValue('A revised scene with exact visual continuity.');
  await page.getByRole('button', { name: /Render queue/ }).click();
  await expect(page.getByText('Queued', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
test('browses a nested server workflow and exposes node settings', async ({ page }) => {
  await page.goto('/'); await expect(page.getByRole('button', { name: 'Server library' })).toBeEnabled();
  await page.getByRole('button', { name: 'Server library' }).click();
  await page.getByRole('button', { name: 'H3/Test workflow.json' }).click();
  await expect(page.getByRole('textbox', { name: 'Project name' })).toHaveValue('H3/Test workflow');
  await page.locator('.viewer-tabs').getByRole('button', { name: 'Workflow', exact: true }).click();
  await page.locator('.workflow-node').filter({ hasText: 'MiniMaxH3ChainPlan' }).first().click();
  await expect(page.getByLabel('run name', { exact: true })).toHaveValue('sceneweaver_first_film');
  await page.getByLabel('width', { exact: true }).fill('1280'); await page.getByLabel('width', { exact: true }).press('Tab');
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export API', exact: true }).click();
  expect((await download).suggestedFilename()).toBe('workflow.api.json');
});
test('reports connection failures without losing the project', async ({ page }) => {
  await page.goto('/'); await expect(page.getByRole('button', { name: 'Render workflow', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Connection settings' }).click();
  await page.getByRole('textbox', { name: 'ComfyUI server address' }).fill('http://127.0.0.1:1');
  await page.getByRole('button', { name: 'Connect', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Cannot reach ComfyUI');
  await expect(page.getByRole('textbox', { name: 'Scene direction', exact: true })).not.toHaveValue('');
  await expect(page.getByRole('button', { name: 'Render workflow', exact: true })).toBeDisabled();
});
test('recovers the event connection and cancels only its queued prompt', async ({ page, request }) => {
  await page.goto('/');
  const render = page.getByRole('button', { name: 'Render workflow', exact: true });
  await expect(render).toBeEnabled();
  await request.post('/comfy/test/disconnect');
  await expect(render).toBeDisabled();
  await expect(render).toBeEnabled({ timeout: 10000 });
  await render.click();
  await expect(page.getByText('Queued', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Stop this render' }).click();
  await expect(page.getByText('Cancelled', { exact: true })).toBeVisible();
  expect((await (await request.get('/comfy/queue')).json()).queue_pending).toHaveLength(0);
});
test('syncs an exact rerolled seed into the project', async ({ page, request }) => {
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Render workflow', exact: true })).toBeEnabled();
  await request.post('/comfy/test/review');
  await expect(page.getByRole('button', { name: 'Reroll', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Reroll', exact: true }).click();
  await expect(page.getByText('Awaiting your review')).not.toBeVisible();
  await page.getByRole('button', { name: 'Close render queue' }).click();
  await expect(page.getByRole('textbox', { name: 'Scene seed', exact: true })).toHaveValue('18446744073709551614');
});
test('keeps the editor reachable on a narrow screen', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto('/');
  await expect(page.getByRole('textbox', { name: 'Scene direction', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/tablet.png', fullPage: true });
});

test('saved reviews from a stopped render cannot send generation decisions', async ({ page, request }) => {
  await request.post('/comfy/test/reset');
  await page.route('**/minimax_h3_context_loop/reviews', route => route.fulfill({ json: { reviews: [{ token: 'saved-review', run_name: 'sceneweaver_first_film', clip_index: 1, actionable: false, durable: true, recovery_instructions: 'Resume from the saved checkpoint in ComfyUI.', candidates: [{ revision: 'a'.repeat(32) }] }] } }));
  await page.goto('/');
  await expect(page.getByText('Saved review · resume in ComfyUI', { exact: true })).toBeVisible();
  for (const name of ['Approve & continue', 'Retry', 'Reroll', 'Approve & stop']) await expect(page.getByRole('button', { name, exact: true })).toBeDisabled();
  await expect(page.getByText('Resume from the saved checkpoint in ComfyUI.', { exact: true })).toBeVisible();
  expect((await (await request.get('/comfy/test/state')).json()).decisions).toEqual([]);
});
