import { test, expect, type Page } from '@playwright/test';
let target = '';
test.beforeAll(async ({ request }) => { target = (await (await request.get('/api/connection')).json()).target; });
test.beforeEach(async ({ request }) => { await request.put('/api/connection', { data: { target } }); await request.post('/comfy/test/reset'); });
async function attach(page: Page) {
  await page.goto(`${target}/test/live`);
  await page.waitForFunction(() => Boolean((window as any).testComfy));
  await page.evaluate(() => { const item = (window as any).testComfy.graph._nodes.find((n: any) => n.id === '1700').widgets.find((w: any) => w.name === 'plan_json'); const plan = JSON.parse(item.value); plan.shots[0].prompt = 'Unsaved direction from ComfyUI'; item.value = JSON.stringify(plan); });
  const opened = page.waitForEvent('popup'); await page.getByRole('button', { name: 'Open companion' }).click();
  const companion = await opened;
  await expect(companion.getByText('Attached to live workflow', { exact: true })).toBeVisible({ timeout: 15000 });
  return companion;
}
const nativeDirection = (page: Page) => page.evaluate(() => JSON.parse((window as any).testComfy.graph._nodes.find((n: any) => n.id === '1700').widgets.find((w: any) => w.name === 'plan_json').value).shots[0].prompt);
test('requires an explicit production Plan when another authoring Plan appears', async ({ page }) => {
  const companion = await attach(page);
  await page.evaluate(() => {
    const graph = (window as any).testComfy.graph, original = graph._nodes.find((node: any) => node.id === '1700');
    graph._nodes.push({ ...original, id: 'second-plan', title: 'Second production', widgets: original.widgets.map((item: any) => ({ ...item })), inputs: original.inputs.map((item: any) => ({ ...item })) });
  });
  await expect(companion.getByText('Select the production Plan', { exact: true })).toBeVisible();
  await expect(companion.getByRole('button', { name: 'Queue in ComfyUI' })).toBeDisabled();
  await companion.getByRole('combobox', { name: 'Active H3 plan' }).selectOption('1700');
  await expect(companion.getByText('Project binding verified', { exact: true })).toBeVisible();
  await expect(companion.getByRole('textbox', { name: 'Scene direction', exact: true })).toHaveValue('Unsaved direction from ComfyUI');
  await expect(companion.getByRole('button', { name: 'Queue in ComfyUI' })).toBeEnabled();
});

test('recovers a completed save receipt after the companion loses its result and reloads', async ({ page }) => {
  const companion = await attach(page);
  await page.evaluate(() => {
    const store = (window as any).testComfy.extensionManager.workflow, original = store.saveWorkflow;
    (window as any).saveCalls = 0;
    store.saveWorkflow = async (workflow: any) => { (window as any).saveCalls++; await original(workflow); };
  });
  await companion.evaluate(() => window.addEventListener('message', event => {
    if (event.data?.protocol === 'sceneweaver.live.v1' && event.data.kind === 'result' && event.data.result?.saved) event.stopImmediatePropagation();
  }, { capture: true }));
  await companion.getByRole('button', { name: 'Save workflow', exact: true }).click();
  await expect(companion.locator('.command-history summary')).toHaveText('Actions · Completed');
  await companion.reload();
  await expect(companion.getByText('Attached to live workflow', { exact: true })).toBeVisible();
  await companion.locator('.command-history summary').click();
  await expect(companion.locator('.command-history article')).toContainText('Save workflow');
  await expect(companion.locator('.command-history article')).toContainText('Completed');
  expect(await page.evaluate(() => (window as any).saveCalls)).toBe(1);
});

test('checking an uncertain queue result never resubmits generation', async ({ page, request }) => {
  const companion = await attach(page);
  await page.evaluate(() => {
    const app = (window as any).testComfy, original = app.queuePrompt;
    app.queuePrompt = async () => { await original(); throw new Error('Native response lost after submission'); };
  });
  await companion.getByRole('button', { name: 'Queue in ComfyUI' }).click();
  await expect(companion.locator('.command-history summary')).toHaveText('Actions · Result unknown');
  await companion.locator('.command-history summary').click();
  await companion.getByRole('button', { name: 'Check result', exact: true }).click();
  await expect(companion.getByRole('button', { name: 'Check result', exact: true })).toBeEnabled();
  expect((await (await request.get('/comfy/test/state')).json()).submissions).toHaveLength(1);
  await companion.reload();
  await expect(companion.locator('.command-history summary')).toHaveText('Actions · Result unknown');
  expect((await (await request.get('/comfy/test/state')).json()).submissions).toHaveLength(1);
});

test('edits the wired Carousel through Get/Set even when another Carousel has the same project name', async ({ page }) => {
  const companion = await attach(page);
  await page.evaluate(() => {
    const graph = (window as any).testComfy.graph, manager = graph._nodes.find((node: any) => node.id === '9000');
    graph._nodes.push({ ...manager, id: '9001', title: 'Bound project assets', widgets: manager.widgets.map((item: any) => ({ ...item })), inputs: [] });
    graph._nodes.push({ id: 'get-assets', type: 'GetNode', graph, widgets: [{ name: 'Constant', value: 'project-assets' }], inputs: [] });
    graph._nodes.push({ id: 'set-assets', type: 'SetNode', graph, widgets: [{ name: 'Constant', value: 'project-assets' }], inputs: [{ name: '*', link: 90001 }] });
    graph.links[90001] = { origin_id: '9001', origin_slot: 0 };
    graph.links[90002] = { origin_id: 'get-assets', origin_slot: 0 };
    graph._nodes.find((node: any) => node.id === '1700').inputs.push({ name: 'project_assets', link: 90002 });
  });
  await companion.locator('.workflow-binding summary').click();
  await expect(companion.locator('.binding-details')).toContainText('Bound project assets');
  await companion.locator('.viewer-tabs').getByRole('button', { name: 'Assets', exact: true }).click();
  await companion.getByRole('textbox', { name: 'Tag for hero', exact: true }).fill('bound-hero');
  await companion.getByRole('button', { name: 'Apply', exact: true }).click();
  await expect(companion.getByRole('textbox', { name: 'Tag for bound-hero', exact: true })).toBeVisible();
  const catalogs = await page.evaluate(() => (window as any).testComfy.graph._nodes.filter((node: any) => ['9000', '9001'].includes(node.id)).map((node: any) => node.widgets.find((item: any) => item.name === 'catalog_json').value));
  expect(catalogs[0]).toBe('{}'); expect(JSON.parse(catalogs[1]).assets[0].tag).toBe('bound-hero');
});

test('attaches unsaved state, explicitly applies a prompt, queues natively, and exports the original canvas', async ({ page, request }) => {
  const companion = await attach(page), errors: string[] = []; companion.on('pageerror', e => errors.push(e.message));
  const direction = companion.getByRole('textbox', { name: 'Scene direction', exact: true });
  await expect(direction).toHaveValue('Unsaved direction from ComfyUI');
  await direction.fill('Companion direction');
  await expect(companion.getByRole('button', { name: 'Save workflow', exact: true })).toBeDisabled();
  await expect(companion.getByRole('button', { name: 'Queue in ComfyUI' })).toBeDisabled();
  expect(await nativeDirection(page)).toBe('Unsaved direction from ComfyUI');
  await companion.getByRole('button', { name: 'Apply to ComfyUI', exact: true }).click();
  await expect(companion.getByText('Attached to live workflow', { exact: true })).toBeVisible();
  expect(await nativeDirection(page)).toBe('Companion direction');
  expect(await page.evaluate(() => (window as any).nativeCallbacks)).toBeGreaterThan(0);
  await companion.getByRole('button', { name: 'Save workflow', exact: true }).click();
  await expect(companion.getByText('Saved workflows/Live unsaved.json', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => JSON.parse((window as any).savedWorkflow.graph.nodes.find((node: any) => node.id === '1700').widgets_values.find((value: any) => typeof value === 'string' && value.includes('Companion direction'))).shots[0].prompt)).toBe('Companion direction');
  await companion.getByRole('button', { name: 'Queue in ComfyUI' }).click();
  await expect(companion.getByText('Queued', { exact: true })).toBeVisible();
  const state = await (await request.get('/comfy/test/state')).json();
  expect(state.submissions[0].client_id).toBe('native-comfy-client');
  expect(state.submissions[0].extra_data.native_queue_hook).toBe(true);
  const download = companion.waitForEvent('download'); await companion.getByRole('button', { name: 'Export workflow', exact: true }).click();
  expect((await download).suggestedFilename()).toContain('Live unsaved');
  expect(await companion.evaluate(() => localStorage.getItem('sceneweaver.project.v1'))).toBeNull();
  expect(errors).toEqual([]);
});
test('preserves a draft on conflicting native edits and blocks writes after a tab switch', async ({ page }) => {
  const companion = await attach(page), direction = companion.getByRole('textbox', { name: 'Scene direction', exact: true });
  await direction.fill('Preserve this local draft');
  await page.evaluate(() => { const item = (window as any).testComfy.graph._nodes.find((n: any) => n.id === '1700').widgets.find((w: any) => w.name === 'plan_json'); const plan = JSON.parse(item.value); plan.shots[0].prompt = 'Changed in ComfyUI'; item.value = JSON.stringify(plan); });
  await expect(companion.getByText('Concurrent edit detected', { exact: true })).toBeVisible();
  await expect(direction).toHaveValue('Preserve this local draft');
  await expect(companion.getByRole('button', { name: 'Apply to ComfyUI', exact: true })).toBeDisabled();
  expect(await nativeDirection(page)).toBe('Changed in ComfyUI');
  await companion.getByRole('button', { name: 'Reload from ComfyUI' }).click();
  await expect(direction).toHaveValue('Changed in ComfyUI');
  await page.evaluate(() => { (window as any).testComfy.extensionManager.workflow.activeWorkflow = { path: 'workflows/Other.json', filename: 'Other.json' }; });
  await expect(companion.getByText('ComfyUI tab changed', { exact: true })).toBeVisible();
  await expect(companion.getByRole('button', { name: 'Queue in ComfyUI' })).toBeDisabled();
  await companion.getByRole('button', { name: 'Attach current tab' }).click();
  await expect(companion.getByRole('textbox', { name: 'Project name' })).toHaveValue('Other.json');
});
test('manages the native project catalog and reads saved checkpoint metadata', async ({ page }) => {
  const companion = await attach(page);
  await companion.locator('.viewer-tabs').getByRole('button', { name: 'Assets', exact: true }).click();
  await expect(companion.getByRole('textbox', { name: 'Tag for hero', exact: true })).toBeEnabled();
  await companion.getByRole('textbox', { name: 'Tag for hero', exact: true }).fill('lead');
  await companion.getByRole('button', { name: 'Apply', exact: true }).click();
  await expect(companion.getByRole('textbox', { name: 'Tag for lead', exact: true })).toHaveValue('lead');
  expect(await page.evaluate(() => JSON.parse((window as any).testComfy.graph._nodes.find((n: any) => n.id === '9000').widgets.find((w: any) => w.name === 'catalog_json').value).assets[0].tag)).toBe('lead');
  await companion.locator('.viewer-tabs').getByRole('button', { name: 'Takes', exact: true }).click();
  await expect(companion.getByText('Active take', { exact: true })).toBeVisible();
  await expect(companion.getByText('Seed 18446744073709551615', { exact: true })).toBeVisible();
  const download = companion.waitForEvent('download'); await companion.getByRole('button', { name: 'Export checkpoint list' }).click();
  expect((await download).suggestedFilename()).toBe('sceneweaver_first_film.checkpoints.json');
  await companion.screenshot({ path: 'test-results/live-companion.png', fullPage: true });
});
test('follows an already queued project and receives progress from its original browser client', async ({ page, request }) => {
  const prompt = await (await request.get('/comfy/test/starter')).json();
  const queued = await (await request.post('/comfy/prompt', { data: { prompt, client_id: 'native-comfy-client' } })).json();
  const companion = await attach(page);
  await companion.getByRole('button', { name: /Render queue/ }).click();
  await expect(companion.getByText('Queued', { exact: true })).toBeVisible();
  await page.evaluate(async id => { const { api } = await import('/scripts/api.js'); api.dispatchEvent(new CustomEvent('progress', { detail: { prompt_id: id, value: 7, max: 10, node: '1701' } })); }, queued.prompt_id);
  await expect(companion.getByText('Rendering', { exact: true })).toBeVisible();
  await expect(companion.locator('.job-card progress')).toHaveAttribute('value', '0.7');
});
test('ignores unpaired messages and preserves drafts when the ComfyUI page closes', async ({ page }) => {
  const companion = await attach(page);
  await companion.evaluate(() => window.postMessage({ protocol: 'sceneweaver.live.v1', session: 'wrong-session', kind: 'snapshot', snapshot: { binding: 'wrong', name: 'Injected workflow', nodes: {} } }, location.origin));
  await expect(companion.getByRole('textbox', { name: 'Project name' })).toHaveValue('Live unsaved.json');
  await companion.getByRole('textbox', { name: 'Scene direction', exact: true }).fill('Keep after disconnect');
  await page.close();
  await expect(companion.getByText('Waiting for the ComfyUI tab', { exact: true })).toBeVisible({ timeout: 8000 });
  await expect(companion.getByRole('button', { name: 'Apply to ComfyUI', exact: true })).toBeDisabled();
  await expect(companion.getByRole('textbox', { name: 'Scene direction', exact: true })).toHaveValue('Keep after disconnect');
  await expect(companion.getByRole('button', { name: 'Export draft', exact: true })).toBeEnabled();
});
test('plays the final-cut alternate with separate audio, source music, and timed captions', async ({ page, request }) => {
  await request.post('/comfy/test/playback');
  const companion = await attach(page);
  const video = companion.locator('.viewer-canvas video');
  await expect(video).toHaveAttribute('src', /final-alt.webm/);
  const generated = companion.getByTestId('generated-audio'), source = companion.getByTestId('source-audio');
  await expect(generated).toHaveAttribute('src', /base.wav/);
  await expect(source).toHaveAttribute('src', /source-audio/);
  await expect(companion.getByTestId('subtitle-overlay')).toHaveText('First scene caption');
  await companion.screenshot({ path: 'test-results/playback-viewer.png', fullPage: true });
  await expect.poll(() => video.evaluate((e: HTMLVideoElement) => e.readyState)).toBeGreaterThanOrEqual(2);
  await companion.getByRole('button', { name: 'Play preview', exact: true }).click();
  await expect.poll(() => generated.evaluate((e: HTMLAudioElement) => e.paused)).toBe(false);
  await expect.poll(() => source.evaluate((e: HTMLAudioElement) => e.paused)).toBe(false);
  expect(await video.evaluate((e: HTMLVideoElement) => e.muted)).toBe(true);
  await companion.getByRole('button', { name: 'Pause preview', exact: true }).click();
  await expect.poll(() => source.evaluate((e: HTMLAudioElement) => e.paused)).toBe(true);
  await companion.getByRole('checkbox', { name: 'Source soundtrack', exact: true }).uncheck();
  expect(await source.evaluate((e: HTMLAudioElement) => e.muted)).toBe(true);
  await companion.getByRole('button', { name: 'Toggle subtitles' }).click();
  await expect(companion.getByTestId('subtitle-overlay')).not.toBeVisible();
  await companion.getByRole('combobox', { name: 'Preview scene take' }).selectOption('base');
  await expect(video).toHaveAttribute('src', /base.webm/);
  await expect.poll(() => generated.evaluate((e: HTMLAudioElement) => e.paused)).toBe(true);
});
test('keeps captions and source music aligned after editorial trims, gaps, and scene seeking', async ({ page, request }) => {
  await request.post('/comfy/test/playback');
  const companion = await attach(page);
  await companion.getByRole('button', { name: 'Next scene', exact: true }).click();
  await expect(companion.locator('.viewer-canvas video')).toHaveAttribute('src', /second.webm/);
  await expect(companion.getByTestId('subtitle-overlay')).toHaveText('Second scene caption');
  await expect(companion.locator('.timeline-clock')).toHaveText('Sequence 00:00:10:00');
  const source = companion.getByTestId('source-audio');
  await expect.poll(() => source.evaluate((e: HTMLAudioElement) => e.currentTime)).toBeCloseTo(12, 1);
  await companion.getByRole('slider', { name: 'Seek sequence' }).fill('11');
  await expect.poll(() => source.evaluate((e: HTMLAudioElement) => e.currentTime)).toBeCloseTo(13, 1);
  await expect(companion.locator('.timeline-clock')).toHaveText('Sequence 00:00:11:00');
  await companion.getByRole('button', { name: 'All takes (0 alternates)' }).click();
  await expect(companion.getByRole('combobox', { name: 'Filter checkpoint scenes' })).toHaveValue('2');
  await companion.screenshot({ path: 'test-results/playback-takes.png', fullPage: true });
});

test('continues across a trimmed ending and a gap without replacing the source soundtrack', async ({ page, request }) => {
  await request.post('/comfy/test/playback');
  const companion = await attach(page), seek = companion.getByRole('slider', { name: 'Seek sequence' });
  await expect(companion.getByRole('button', { name: 'Sequence', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await companion.getByTestId('source-audio').evaluate(element => { (window as any).originalSoundtrack = element; });
  await seek.fill('1.75');
  await companion.getByRole('button', { name: 'Play preview', exact: true }).click();
  await expect(companion.getByRole('heading', { name: 'Timeline gap' })).toBeVisible();
  await expect.poll(() => seek.inputValue().then(Number)).toBeGreaterThan(2.1);
  await expect(companion.getByTestId('subtitle-overlay')).not.toBeVisible();
  expect(await companion.getByTestId('source-audio').evaluate(element => element === (window as any).originalSoundtrack)).toBe(true);
  await expect.poll(() => companion.getByTestId('source-audio').evaluate((e: HTMLAudioElement) => e.paused)).toBe(false);
  await companion.locator('.viewer-empty h2').click(); await companion.keyboard.press('Space');
  await expect(companion.getByRole('button', { name: 'Play preview', exact: true })).toBeVisible();
  const paused = Number(await seek.inputValue()); await companion.waitForTimeout(250);
  expect(Number(await seek.inputValue())).toBe(paused);
  await seek.fill('9.75');
  await companion.getByRole('button', { name: 'Play preview', exact: true }).click();
  await expect(companion.locator('.viewer-canvas video')).toHaveAttribute('src', /second.webm/);
  await expect(companion.getByTestId('generated-audio')).toHaveAttribute('src', /second.wav/);
  await expect(companion.getByTestId('subtitle-overlay')).toHaveText('Second scene caption');
  await expect.poll(() => seek.inputValue().then(Number)).toBeGreaterThan(10.1);
  await companion.getByRole('button', { name: 'Pause preview', exact: true }).click();
  const global = Number(await seek.inputValue());
  expect(await companion.getByTestId('source-audio').evaluate((e: HTMLAudioElement) => e.currentTime)).toBeCloseTo(global + 2, 0);
  await companion.screenshot({ path: 'test-results/continuous-sequence.png', fullPage: true });
});
test('advances directly to an adjacent scene and releases the previous picture and generated audio', async ({ page, request }) => {
  await request.post('/comfy/test/playback', { data: { adjacent: true } });
  const companion = await attach(page);
  await companion.locator('.viewer-canvas video').evaluate(element => { (window as any).oldPicture = element; });
  await companion.getByTestId('generated-audio').evaluate(element => { (window as any).oldGenerated = element; });
  await companion.getByRole('slider', { name: 'Seek sequence' }).fill('1.75');
  await companion.getByRole('button', { name: 'Play preview', exact: true }).click();
  await expect(companion.locator('.viewer-canvas video')).toHaveAttribute('src', /second.webm/);
  await expect.poll(() => companion.getByRole('slider', { name: 'Seek sequence' }).inputValue().then(Number)).toBeGreaterThan(2.15);
  expect(await companion.evaluate(() => [(window as any).oldPicture.paused, (window as any).oldGenerated.paused])).toEqual([true, true]);
  await expect.poll(() => companion.getByTestId('generated-audio').evaluate((e: HTMLAudioElement) => e.paused)).toBe(false);
  await companion.getByRole('button', { name: 'Previous scene', exact: true }).click();
  await expect(companion.locator('.viewer-canvas video')).toHaveAttribute('src', /final-alt.webm/);
  await expect(companion.getByRole('button', { name: 'Play preview', exact: true })).toBeVisible();
  await expect(companion.getByRole('slider', { name: 'Seek sequence' })).toHaveValue('0');
});
test('clip mode stops at its trim and choosing another take pauses playback', async ({ page, request }) => {
  await request.post('/comfy/test/playback');
  const companion = await attach(page);
  await companion.getByRole('button', { name: 'Clip', exact: true }).click();
  await companion.getByRole('slider', { name: 'Seek preview' }).fill('1.75');
  await companion.getByRole('button', { name: 'Play preview', exact: true }).click();
  await expect(companion.getByRole('button', { name: 'Play preview', exact: true })).toBeVisible();
  await expect(companion.getByRole('slider', { name: 'Seek preview' })).toHaveValue('2');
  await expect(companion.locator('.viewer-canvas video')).toHaveAttribute('src', /final-alt.webm/);
  await companion.getByRole('button', { name: 'Play preview', exact: true }).click();
  await companion.getByRole('combobox', { name: 'Preview scene take' }).selectOption('base');
  await expect(companion.getByRole('button', { name: 'Clip', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(companion.getByRole('button', { name: 'Play preview', exact: true })).toBeVisible();
  await expect(companion.getByRole('slider', { name: 'Seek preview' })).toHaveValue('0');
  await companion.getByRole('button', { name: 'Sequence', exact: true }).click();
  await expect(companion.locator('.viewer-canvas video')).toHaveAttribute('src', /final-alt.webm/);
});
test('plays an unrendered scene to the sequence end, then restarts with Space and stops on leaving the viewer', async ({ page, request }) => {
  await request.post('/comfy/test/playback');
  const companion = await attach(page), seek = companion.getByRole('slider', { name: 'Seek sequence' });
  const end = Number(await seek.getAttribute('max'));
  await seek.fill('25');
  await expect(companion.getByText(/No saved video for this scene yet/)).toBeVisible();
  await companion.getByRole('button', { name: 'Play preview', exact: true }).click();
  await expect(companion.getByRole('button', { name: 'Play preview', exact: true })).toBeVisible();
  expect(Number(await seek.inputValue())).toBeCloseTo(end, 1);
  await expect.poll(() => companion.getByTestId('source-audio').evaluate((e: HTMLAudioElement) => e.paused)).toBe(true);
  await companion.locator('.viewer-empty h2').click(); await companion.keyboard.press('Space');
  await expect(companion.locator('.viewer-canvas video')).toHaveAttribute('src', /final-alt.webm/);
  await expect.poll(() => seek.inputValue().then(Number)).toBeGreaterThan(.1);
  expect(Number(await seek.inputValue())).toBeLessThan(2);
  await companion.getByTestId('source-audio').evaluate(element => { (window as any).lastSoundtrack = element; });
  await companion.locator('.viewer-tabs').getByRole('button', { name: 'Assets', exact: true }).click();
  expect(await companion.evaluate(() => (window as any).lastSoundtrack.paused)).toBe(true);
});
